version: "3"

services:
  solargatewayproxy:
    container_name: solargatewayproxy
    image: ghcr.io/dresteban/solargateway_prometheusproxy:latest
    ports:
      - 5026:8080
    environment:
      - "Tesla__Enabled=true"
      - "Tesla__Email=<email>"
      - "Tesla__Password=<password>"
      - "Tesla__Host=<ip of the gateway>"
      - "Tesla__LoginCacheMinutes=10"
      - "ResponseCacheDurationSeconds=3"
      - "Logging__Console__TimestampFormat=[MM/dd/yy h:mm:ss tt] "
      - "APPLICATIONINSIGHTS_CONNECTION_STRING=<optional: if you want to log to Azure>"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0:0"
    ports:
      - 9090:9090
    volumes:
      - '/prometheus/prometheus:/prometheus'
      - '/prometheus/prometheus.yml:/config/prometheus.yml'
    command:
      - '--config.file=/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=3650d'
    depends_on:
      - solargatewayproxy
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0:0"
    command:
      - '--config=/etc/grafana/grafana_custom.ini'
    ports:
      - 3001:3001
    volumes:
      - '/prometheus/grafana:/var/lib/grafana'
      - '/prometheus/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml'
      - '/prometheus/grafana_custom.ini:/etc/grafana/grafana_custom.ini'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=<password for admin user>
      - GF_SERVER_ROOT_URL=<url to access grafana, if you're using a reverse proxy>
    depends_on:
      - prometheus
    restart: unless-stopped