{
 "title": "Powerwall",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current solar production",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_solar_instant_power / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current house draw",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_load_instant_power / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current grid draw",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_site_instant_power / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Powerwall discharge state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_battery_instant_power / 1000 * -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerwall charge %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_powerwall_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar energy generated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tesla_gateway_solar_energy_exported[$__range]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid energy exported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tesla_gateway_site_energy_exported[$__range]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid energy imported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tesla_gateway_site_energy_imported[$__range]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "tesla_gateway_solar_instant_power / 1000",
     "legendFormat": "Solar"
    }
   ]
  },
  {
   "title": "Powerwall charge/discharge state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "tesla_gateway_battery_instant_power / 1000 * -1",
     "legendFormat": "Power flow"
    }
   ]
  },
  {
   "title": "House power draw",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "tesla_gateway_load_instant_power / 1000",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Powerwall charge %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tesla_gateway_powerwall_percentage",
     "legendFormat": "Battery %"
    }
   ]
  },
  {
   "title": "Run mode",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(label_replace(tesla_gateway_operation_mode{mode=~\"autonomous|self_consumption\"}, \"mode\", \"Time-based\", \"mode\", \"autonomous\"), \"mode\", \"Self powered\", \"mode\", \"self_consumption\")",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Grid power draw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "tesla_gateway_site_instant_power / 1000",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_status_up_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_gateway_status_start_time * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "tesla_gateway_apiproxy_request_duration_ms{loginCached=~\"false|true\"}",
     "legendFormat": "Login cached {{loginCached}}"
    }
   ]
  },
  {
   "title": "Average login-cached request duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(tesla_gateway_apiproxy_request_duration_ms{loginCached=\"true\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}